### ISSUE TITLE
Como administrador quiero editar la información de un evento creado

### ISSUE THREAD

**Issue by VaniMar** [GDGCochabamba/events-platform#13]

**Comment by juliosguz** [comment]
**Escenario 1 - En la lista de eventos**
Dado que estamos en la lista de eventos y cuando presionamos en un evento entonces nos mostrara el formulario "user edit".

**Escenario 2 - En el formulario de edición**
Dado que estamos en formulario de edición con la información del evento cargado en los campos del formulario, cuando se termine de editar los campos y se presione el boton "save" entonces se redireccionará a la vista "list event"
