### ISSUE TITLE
Como administrador quiero crear una cuenta de usuario tal que luego de guardar me redireccione al perfil

### ISSUE THREAD

**Issue by VaniMar** [GDGCochabamba/events-platform#19]

**Comment by juliosguz** [comment]
@MartinArispeRiveros 
Escenario 1 - Al llenar formulario
Dado que estamos en el formulario "create user" que tendrá los siguientes campos: firstName, lastName, birthDate, phone y gender(M,F) cuando llene los campos y presione el boton "Save" entonces me redireccionara a la pagina "view profile".

Escenario 2 - Al presionar el boton "Save"
Dado que estamos en el formulario "create user" y se ha presionado el boton "save", se creara un nuevo usuario en Firebase y se agregara un registro a la colección "profiles" entonces cada registro de la colección "profiles" tendrá los siguientes campos: firstName, lastName, birthDate, phone y gender(M,F)

**Comment by juliosguz** [comment]
Dado que estamos en el formulario "create user" y se ha presionado el boton "save", se creara un nuevo usuario en Firebase y se agregara un registro a la colección "profiles" entonces cada registro de la colección "profiles" tendrá los siguientes campos: firstName, lastName, birthDate, phone y gender(M,F)

**Comment by MartinArispeRiveros** [comment]
@juliosguz ya esta completo esta funcionalidad, por favor pruebalo para hacer el merge a la rama principal y se den estilos a las vistas.
Se puede testear siguiendo las siguientes direcciones
Crear profile : http://localhost:3000/add-profile
Ver profile: http://localhost:3000/view-profile
Estoy atento a tus obsrvaciones.

**Comment by juliosguz** [comment]
Lo revise y esta funcionando bien, acepto el pull request y te agrego a la siguiente tarea
