### ISSUE TITLE
Como administrador quiero ver integrado con la navegación la sección profiles tal que sea mas sencillo usar sus funcionalidades

### ISSUE THREAD

**Issue by juliosguz** [GDGCochabamba/events-platform#42]

**Comment by juliosguz** [comment]
@MartinArispeRiveros 
- Tanto el add-profile y view-profile, tiene que verse dentro de la seccion principal. Revisa como esta eventos para que puedas usar ui-router
- En la navegación de la izquierda, agrega un enlace para ver los perfiles / #43 
- Dentro del listado, agrega un enlace a poder entrar a add-profile, podrias revisar como esta ahora en eventos

**Comment by MartinArispeRiveros** [comment]
@juliosguz , @jdasin I solved this task and i send you the pull request, if you need more info send me a message.
